### ISSUE TITLE
User can draw "off" the sketchpad 

### ISSUE THREAD

**Issue by JenniferToops** [meera-ramesh19/mintbean-hackathon#4]
The sketchpad container needs to be adjusted so that the user can only draw within the designated canvas space (or remove the container so that the user can draw in the white space).

This is the branch I pulled from main and deployed to Netlify that illustrates the issue:
https://www.loom.com/share/8f75087e921946c3a7972b1c0d27b185

**Comment by meera-ramesh19** [comment]
fixed it
